/**
 * Professional Report Generator
 * Handles creation of professional, formatted CSV and data exports
 */

const formatDate = (date) => {
  if (!date) return '';
  if (typeof date === 'string') {
    try {
      return new Date(date).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
    } catch (e) {
      return date;
    }
  }
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
};

const formatDateTime = (date) => {
  if (!date) return '';
  if (typeof date === 'string') {
    try {
      return new Date(date).toLocaleString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
      });
    } catch (e) {
      return date;
    }
  }
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
};

const escapeCSV = (value) => {
  if (value === null || value === undefined) return '';
  const stringValue = String(value);
  if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
    return `"${stringValue.replace(/"/g, '""')}"`;
  }
  return stringValue;
};

/**
 * Generate professional CSV with headers and formatted data
 */
const generateCSV = (reportData) => {
  const {
    title = 'Report',
    subtitle = '',
    generatedBy = 'Medical Inventory System',
    generatedAt = new Date(),
    columns = [],
    data = [],
    summaryStats = [],
    footer = '',
  } = reportData;

  const lines = [];

  // Header section
  lines.push(`"${title}"`);
  if (subtitle) {
    lines.push(`"${subtitle}"`);
  }
  lines.push(''); // Blank line

  // Metadata section
  lines.push(`"Report Generated: ${formatDateTime(generatedAt)}"`);
  lines.push(`"Generated By: ${generatedBy}"`);
  lines.push(''); // Blank line

  // Column headers
  lines.push(columns.map(escapeCSV).join(','));

  // Data rows
  data.forEach((row) => {
    const values = columns.map((col) => {
      const value = typeof row === 'object' ? row[col] : '';
      return escapeCSV(value);
    });
    lines.push(values.join(','));
  });

  // Summary statistics
  if (summaryStats && summaryStats.length > 0) {
    lines.push(''); // Blank line
    lines.push('"SUMMARY STATISTICS"');
    summaryStats.forEach(({ label, value }) => {
      lines.push(`"${label}","${escapeCSV(value)}"`);
    });
  }

  // Footer
  if (footer) {
    lines.push(''); // Blank line
    lines.push(`"${footer}"`);
  }

  return lines.join('\n');
};

/**
 * Trigger download of CSV file
 */
const downloadCSV = (filename, csvContent) => {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `report-${new Date().getTime()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
};

/**
 * Download report with professional formatting
 */
export const downloadReport = (filename, reportData) => {
  const csv = generateCSV(reportData);
  downloadCSV(filename, csv);
};

export { formatDate, formatDateTime, escapeCSV, generateCSV };
